### ISSUE TITLE
add OS open roads sample data

### ISSUE THREAD

**Issue by mpadge** [gmost/dodgr#14]
to show how `dodgr` handles non-OSM street networks. @Robinlovelace wanna PR this? Just put some data there, and I should be able to take care of the rest.

**Comment by Robinlovelace** [comment]
Great stuff - now the mission is to integrate this in the vignette. You up for making a start on that? Or we could go directly for an academic write-up. Your call.

**Comment by mpadge** [comment]
Yeah, i guess this newly expanded functionality should be described in the vignette. I'm also very keen to start an academic write up imminently! 

In the meantime, could you do one more thing, please? Just tidy the man entry for [`os_roads_bristol`](https://github.com/gmost/dodgr/blob/master/R/dodgr-package.r) so it can be run. It currently relies on some `.shp` file that only you have, and also calls some `lad16nm` object that doesn't exist. It would also be good to state at the outset that "these data may be reproduced with the following lines of code." Thanks!

I'll re-open until:
- [ ] 1. vignette updated
- [ ] 2. man entry for `os_roads_bristol` updated

**Comment by Robinlovelace** [comment]
Hi Mark, you can reproduce it by downloading the data from https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-roads.html and running the commands as follows.

However, there's no way to automate the process of delivering the 300 MB file - you need to fill-in an application form.

**Comment by Robinlovelace** [comment]
Demo that it is reproducible generated using **reprex**:

``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.2, lwgeom 2.3.3 r15473
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
os_roads <- sf::read_sf("~/data/roads-data/data/ST_RoadLink.shp")  # data must be unzipped here
u <- "https://opendata.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4.kml"
lads <- sf::read_sf(u)
mapview::mapview(lads)
bristol_pol <- dplyr::filter(lads, grepl("Bristol", lad16nm))
os_roads <- st_transform(os_roads, st_crs(lads))
os_roads_bristol <- os_roads[bristol_pol, ] %>% dplyr::filter(class == "Motorway" & 
  roadNumber != "M32") %>% st_zm(drop = TRUE)
#> although coordinates are longitude/latitude, it is assumed that they are planar
mapview::mapview(os_roads_bristol)
```

**Comment by Robinlovelace** [comment]
Results just tested in new session:

![image](https://user-images.githubusercontent.com/1825120/31008743-109da4cc-a4fd-11e7-8703-20074a26005a.png)

**Comment by Robinlovelace** [comment]
(I love the place name [Catbrain](https://en.wikipedia.org/wiki/Catbrain)).

**Comment by mpadge** [comment]
oh, i see. Can you just describe the process then? Say that you have to register and manually download. I just did the vignette with [this push](https://github.com/gmost/dodgr/commit/55e26032fb60b0b9d4038d16d43dd77c26458156). (Also re-inserted explicit section numbers coz `pkgdown` doesn't respect the `number sections: true` command - i checked on lotsa `tidyverse` packages, and they all omit section numbers, which is dumb!)

**Comment by Robinlovelace** [comment]
Sure.

**Comment by Robinlovelace** [comment]
Final thing: I suggest a visualisation of the a network measure such as centrality would be good to visualise how datasets such as OS Open Roads can be analysed with **dodgr**.

**Comment by mpadge** [comment]
sounds good, but it might be tricky to manage that at present without introducing additional package dependencies? If you can manage it, then great, otherwise I'll ref this in new issue about viz.

**Comment by Robinlovelace** [comment]
Good stuff.
