### ISSUE TITLE
reinstate edge_map for dodgr_contract_graph

### ISSUE THREAD

**Issue by mpadge** [gmost/dodgr#22]
To enable flows to be routed through contracted graphs, but re-allocated to full graphs

**Comment by mpadge** [comment]
Now done as part of #21, but not yet integrated within `dodgr_flows()` to enable re-allocation.0

**Comment by mpadge** [comment]
Integrated with `dodgr_flows()` with [this commit](https://github.com/gmost/dodgr/commit/9503e14c77c89a06c7474a6f1c7e4d2d4d985039), but it doesn't yet work quite correctly:
```
graph <- weight_streetnet (hampi)
verts <- dodgr_vertices (dodgr_contract_graph (graph)$graph)
pts <- sample (verts$id, size = 10)
flows <- matrix (runif (100), nrow = 10)
graph1 <- dodgr_flows (graph, from = pts, to = pts, flows = flows,
                       contract = FALSE)
graph2 <- dodgr_flows (graph, from = pts, to = pts, flows = flows,
                       contract = TRUE)
plot (graph1$flow, graph2$flow, pch = 1, col = "orange")
```
![junk](https://user-images.githubusercontent.com/6697851/31685252-8e2c0314-b382-11e7-8adc-86b96bba312b.png)

Mostly bang on, but a few stray points that need to be fixed

**Comment by mpadge** [comment]
The stray points are cases where the type of way changes along the contracted edges. Contraction currently ignores this, and just allocates the way type of the final contracted edge. This obviously needs to be recitified through ensuring contraction is only implemented along consistent way types. Contracted graphs will then be slightly larger, but the above graph illustrates that this will be a relatively minor increase for the sake of exactness in computing flows.

@Robinlovelace This is the final task for next `dodgr` CRAN release, and will mean flows can be calculated on contracted graphs, and then re-allocated to full graphs. This translates to flow allocation being around 10 times faster!

**Comment by mpadge** [comment]
It's still not fixed ...

**Comment by Robinlovelace** [comment]
Awesome - one to discuss in Leeds I think, a little over my head!

**Comment by mpadge** [comment]
Finally fixed with a bunch of commits, mostly [here](https://github.com/gmost/dodgr/commit/aee72fdc137f20949f82c4834c6036f118a9fb72), [here](https://github.com/gmost/dodgr/commit/c9faaa58db5baf460136f2fa671acc9da7d20313), and [here](https://github.com/gmost/dodgr/commit/96f67f25315cd388fcaa17aac12288c6ea13c04f).

**Comment by Robinlovelace** [comment]
Sweet :fire:
