### ISSUE TITLE
document igraph comparisons using igraphdata package

### ISSUE THREAD

**Issue by mpadge** [gmost/dodgr#8]
@karpfen here's one where you could maybe help out a lot if you wanted to. The `dodgr` manuscript could - likely should - include an empirical section comparing performance for lots of different kinds of graphs (beyond just street networks. I just found the [`igraphdata` package](https://github.com/igraph/igraphdata) which is perfect for the purpose, and `igraph` is sufficiently standardised that it could be used as the sole benchmark. `dodgr` already has the `compare_heaps()` function to do the testing, so it'd just be a matter of running all the graphs though the tests. This would probably best reside (for the moment) in a second vignette.

**Comment by karpfen** [comment]
Sounds good! I'll start on a vignette in my fork for now.

**Comment by mpadge** [comment]
We'll also need to compare full and contracted/compact graphs in all cases, coz that'll likely make quite a difference. I hope to finish contraction code tomorrow ...

**Comment by mpadge** [comment]
thanks @karpfen - all done now!
